# Use this if you're testing/debugging the build locally on OSX

version: "3.4"

services:
  web:
    build:
      context: .
    image: hiondev/nginx:latest
    ports:
      - 8080
    volumes:
      - ./web:/var/www/project/web
